sudo: required
dist: trusty
language: java

before_install:
  - sudo add-apt-repository ppa:wpilib/toolchain -y
  - sudo apt-get update -q || true
  - sudo apt-get install frc-toolchain -y


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    on_success: always
    on_failure: change
    secure: WOingZJ/nk8Mc5JXbHgE5Ux1YwpsrWryft5TH8kPBaIqTmX6qlcu3KSdLktwgiPgXJiOWpR6UitX9+xfalcApEfS77ZNQeUFafDYHv17nS6IAHe/A4vOAIElXfpS2KnY0aqxwWhgKCsehio49SPY7WHq9PtnvauEdkX8bca5FHk=
